### ISSUE TITLE
Build fails on Python WSL

### ISSUE THREAD

**Issue by TimGJ** [TimGJ/PolariBible#1]
It's 10+ years old and things have changed since then... Review and refactor.

```/usr/bin/python3 PickleToLaTeX.py bible.pkl
Writing genesis.tex
Writing genesis.tex
Traceback (most recent call last):
  File "/usr/lib/python3.10/sre_parse.py", line 1051, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\e'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/PolariBible/PickleToLaTeX.py", line 127, in <module>
    ProcessBook(book)
  File "/home/tim/PolariBible/PickleToLaTeX.py", line 106, in ProcessBook
    v.text = pre.sub("\\emph {\g<1>}", v.text)
  File "/usr/lib/python3.10/re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.10/re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.10/sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \e at position 0
make: *** [makefile:55: bible.pdf] Error 1
tim@crowley:~/PolariBible$```

**Comment by TimGJ** [comment]
Removed the old style RCS $Id strings. I'd forgotten how much has changed in the last 10 years or so!

**Comment by TimGJ** [comment]
Build was failing due to a RE which was trying to create TEX output (both interpret backslash and brace characters, so it was always likely to end in tears.

**Comment by TimGJ** [comment]
The next problem is down to the fonts available in WSL not including Times New Roman in whcih the PDF of the Bible was originally produce. I guess there are two options: install the necessary fonts or alter the LaTeX code so it uses an equivalent font.

**Comment by TimGJ** [comment]
That was surprisingly easy to solve. 

`sudo apt install msttcorefonts`
